/* E-Jurnal PKL Rimba Bahari - frontend tanpa proses build */
const cfg = window.APP_CONFIG || {};
const sb = (cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY)
  ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY)
  : null;

const state = { session:null, profile:null, page:'dashboard', students:[], journals:[], attendance:[] };
const $ = (s)=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const roles={admin:'Administrator',student:'Siswa',teacher:'Guru Pembimbing',field_supervisor:'Pembimbing Lapangan'};
const stages=['Perencanaan dan persiapan','Persemaian','Penanaman','Pemeliharaan hutan','Perlindungan hutan','Inventarisasi dan monitoring','Pemanfaatan hutan','Pengelolaan wisata alam','Rehabilitasi hutan','Administrasi dan pelaporan','Pemberdayaan masyarakat','Pengukuran dan pemetaan','Pengelolaan hasil hutan','Keselamatan dan kesehatan kerja','Kegiatan lainnya'];
const menus={
 admin:[['dashboard','Dashboard'],['users','Akun Pengguna'],['students','Data Siswa'],['journals','Semua Jurnal'],['attendance','Presensi'],['reports','Laporan']],
 student:[['dashboard','Dashboard'],['my-journal','Jurnal Harian'],['my-attendance','Presensi Saya'],['reports','Laporan Saya']],
 teacher:[['dashboard','Dashboard'],['journals','Monitoring Jurnal'],['attendance','Kehadiran Siswa'],['reports','Laporan']],
 field_supervisor:[['dashboard','Dashboard'],['journals','Validasi Jurnal'],['attendance','Validasi Presensi'],['reports','Penilaian & Laporan']]
};

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function statusBadge(s){const map={draft:['Draf','gray'],submitted:['Menunggu validasi','yellow'],approved:['Disetujui','green'],revision:['Perlu diperbaiki','red'],rejected:['Ditolak','red']};const x=map[s]||[s,'gray'];return `<span class="badge ${x[1]}">${x[0]}</span>`}
function requireConfig(){if(!sb){$('#loginForm').insertAdjacentHTML('beforebegin','<div class="demo-note" style="margin-bottom:14px;color:#b42318"><strong>Belum dikonfigurasi.</strong> Isi file <code>config.js</code> dengan URL dan Anon Key Supabase.</div>');return false}return true}

async function init(){
 if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
 if(!requireConfig()) return;
 const {data:{session}}=await sb.auth.getSession();
 if(session) await enterApp(session);
 sb.auth.onAuthStateChange(async(_e,s)=>{if(s&&!state.session) await enterApp(s);if(!s) showLogin()});
}

$('#loginForm').addEventListener('submit',async(e)=>{e.preventDefault();if(!sb)return;const email=$('#loginEmail').value.trim();const password=$('#loginPassword').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return toast('Login gagal: '+error.message);await enterApp(data.session)});
$('#logoutBtn').addEventListener('click',()=>sb.auth.signOut());
$('#menuToggle').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));

async function enterApp(session){state.session=session;const {data,error}=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(error||!data){toast('Profil pengguna belum tersedia. Hubungi administrator.');await sb.auth.signOut();return}state.profile=data;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userInfo').textContent=`${data.full_name} • ${roles[data.role]||data.role}`;renderNav();await navigate('dashboard')}
function showLogin(){state.session=null;state.profile=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
function renderNav(){const items=menus[state.profile.role]||menus.student;$('#navMenu').innerHTML=items.map(([id,label])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}">${label}</button>`).join('');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
async function navigate(page){state.page=page;document.querySelector('.sidebar').classList.remove('open');renderNav();const label=(menus[state.profile.role]||[]).find(x=>x[0]===page)?.[1]||'Dashboard';$('#pageTitle').textContent=label;$('#content').innerHTML='<div class="card">Memuat data...</div>';try{if(page==='dashboard')await renderDashboard();else if(page==='users')await renderUsers();else if(page==='students')await renderStudents();else if(page==='journals'||page==='my-journal')await renderJournals();else if(page==='attendance'||page==='my-attendance')await renderAttendance();else await renderReports()}catch(e){console.error(e);$('#content').innerHTML=`<div class="card"><strong>Terjadi kesalahan:</strong> ${esc(e.message)}</div>`}}

async function renderDashboard(){
 const role=state.profile.role;
 let journalQ=sb.from('daily_journals').select('id,status',{count:'exact'});let attQ=sb.from('attendance').select('id',{count:'exact'});
 if(role==='student'){journalQ=journalQ.eq('student_id',state.profile.id);attQ=attQ.eq('student_id',state.profile.id)}
 const [jr,at]=await Promise.all([journalQ,attQ]);const rows=jr.data||[];const approved=rows.filter(x=>x.status==='approved').length;const pending=rows.filter(x=>x.status==='submitted').length;const progress=Math.min(100,Math.round((approved/40)*100));
 $('#content').innerHTML=`<div class="cards">
 <div class="card stat"><strong>${jr.count||0}</strong><span>Total jurnal</span></div>
 <div class="card stat"><strong>${approved}</strong><span>Jurnal disetujui</span></div>
 <div class="card stat"><strong>${pending}</strong><span>Menunggu validasi</span></div>
 <div class="card stat"><strong>${at.count||0}</strong><span>Data presensi</span></div></div>
 <div class="card" style="margin-top:16px"><h3>Progres PKL 40 Hari</h3><div class="progress"><span style="width:${progress}%"></span></div><p>${progress}% jurnal telah disetujui.</p></div>
 <div class="card" style="margin-top:16px"><h3>Selamat datang, ${esc(state.profile.full_name)}</h3><p>Aplikasi ini menyimpan data secara daring. Siswa, guru, pembimbing lapangan, dan administrator dapat mengakses dari jaringan internet yang berbeda.</p></div>`;
}

async function renderUsers(){
 if(state.profile.role!=='admin')return navigate('dashboard');
 const {data,error}=await sb.from('profiles').select('id,full_name,email,role,is_active,created_at').order('full_name');if(error)throw error;
 $('#content').innerHTML=`<div class="section-head"><h3>Akun Pengguna</h3><button class="btn primary" id="addUserBtn">Tambah Akun</button></div>
 <div class="toolbar"><input id="userSearch" placeholder="Cari nama atau email..."><select id="roleFilter"><option value="">Semua peran</option><option value="student">Siswa</option><option value="teacher">Guru</option><option value="field_supervisor">Pembimbing lapangan</option><option value="admin">Administrator</option></select></div>
 <div class="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Peran</th><th>Status</th><th>Tindakan</th></tr></thead><tbody id="userRows"></tbody></table></div>`;
 const draw=()=>{const q=$('#userSearch').value.toLowerCase();const r=$('#roleFilter').value;$('#userRows').innerHTML=data.filter(x=>(!r||x.role===r)&&(`${x.full_name} ${x.email}`.toLowerCase().includes(q))).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td>${esc(roles[x.role]||x.role)}</td><td>${x.is_active?'<span class="badge green">Aktif</span>':'<span class="badge red">Nonaktif</span>'}</td><td><div class="actions"><button class="btn warn reset-pass" data-id="${x.id}" data-name="${esc(x.full_name)}">Reset Password</button><button class="btn secondary edit-profile" data-id="${x.id}">Edit</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Tidak ada data.</td></tr>';bindUserActions(data)};
 $('#userSearch').oninput=draw;$('#roleFilter').onchange=draw;$('#addUserBtn').onclick=()=>openUserModal();draw();
}
function bindUserActions(data){document.querySelectorAll('.reset-pass').forEach(b=>b.onclick=()=>openResetModal(b.dataset.id,b.dataset.name));document.querySelectorAll('.edit-profile').forEach(b=>b.onclick=()=>openEditProfile(data.find(x=>x.id===b.dataset.id)))}
function openUserModal(){modal('Tambah Akun Pengguna',`<form id="userForm" class="form-grid"><label>Nama lengkap<input name="full_name" required></label><label>Email<input name="email" type="email" required></label><label>Peran<select name="role" required><option value="student">Siswa</option><option value="teacher">Guru pembimbing</option><option value="field_supervisor">Pembimbing lapangan</option><option value="admin">Administrator</option></select></label><label>Password awal<input name="password" type="password" minlength="8" required></label><label class="wide">Nomor HP<input name="phone"></label><div class="wide actions"><button class="btn primary">Buat Akun</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);$('#userForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const res=await api('/api/create-user',f);if(res.error)return toast(res.error);closeModal();toast('Akun berhasil dibuat');renderUsers()};bindModalClose()}
function openResetModal(id,name){modal('Reset Password',`<p>Atur password baru untuk <strong>${esc(name)}</strong>.</p><form id="resetForm" class="form-stack"><label>Password baru<input name="new_password" type="password" minlength="8" required></label><label>Ulangi password<input name="confirm" type="password" minlength="8" required></label><div class="actions"><button class="btn warn">Reset Password</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);$('#resetForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.new_password!==f.confirm)return toast('Konfirmasi password tidak sama');const res=await api('/api/reset-password',{user_id:id,new_password:f.new_password});if(res.error)return toast(res.error);closeModal();toast('Password berhasil direset')};bindModalClose()}
function openEditProfile(p){modal('Edit Profil',`<form id="profileForm" class="form-grid"><label>Nama lengkap<input name="full_name" value="${esc(p.full_name)}" required></label><label>Email<input value="${esc(p.email)}" disabled></label><label>Peran<select name="role"><option value="student" ${p.role==='student'?'selected':''}>Siswa</option><option value="teacher" ${p.role==='teacher'?'selected':''}>Guru</option><option value="field_supervisor" ${p.role==='field_supervisor'?'selected':''}>Pembimbing lapangan</option><option value="admin" ${p.role==='admin'?'selected':''}>Administrator</option></select></label><label>Status<select name="is_active"><option value="true" ${p.is_active?'selected':''}>Aktif</option><option value="false" ${!p.is_active?'selected':''}>Nonaktif</option></select></label><div class="wide actions"><button class="btn primary">Simpan</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);$('#profileForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.is_active=f.is_active==='true';const {error}=await sb.from('profiles').update(f).eq('id',p.id);if(error)return toast(error.message);closeModal();toast('Profil diperbarui');renderUsers()};bindModalClose()}

async function renderStudents(){
 if(state.profile.role!=='admin')return navigate('dashboard');
 const {data,error}=await sb.from('student_details').select('*,profiles!student_details_id_fkey(full_name,email),teacher:profiles!student_details_teacher_id_fkey(full_name),field_supervisor:profiles!student_details_field_supervisor_id_fkey(full_name)').order('nis');if(error)throw error;state.students=data||[];
 $('#content').innerHTML=`<div class="section-head"><h3>Data Siswa</h3><button class="btn primary" id="addStudentBtn">Tambah Data Siswa</button></div><div class="table-wrap"><table><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Tempat PKL</th><th>Guru</th><th>Pembimbing Lapangan</th><th>Tindakan</th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${esc(s.nis)}</td><td>${esc(s.profiles?.full_name)}</td><td>${esc(s.class_name)}</td><td>${esc(s.internship_place)}</td><td>${esc(s.teacher?.full_name||'-')}</td><td>${esc(s.field_supervisor?.full_name||'-')}</td><td><button class="btn secondary edit-student" data-id="${s.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Belum ada data siswa.</td></tr>'}</tbody></table></div>`;
 $('#addStudentBtn').onclick=()=>openStudentModal();document.querySelectorAll('.edit-student').forEach(b=>b.onclick=()=>openStudentModal(state.students.find(x=>x.id===b.dataset.id)));
}
async function openStudentModal(existing=null){
 const [{data:students},{data:teachers},{data:fields}]=await Promise.all([sb.from('profiles').select('id,full_name,email').eq('role','student').eq('is_active',true),sb.from('profiles').select('id,full_name').eq('role','teacher').eq('is_active',true),sb.from('profiles').select('id,full_name').eq('role','field_supervisor').eq('is_active',true)]);
 modal(existing?'Edit Data Siswa':'Tambah Data Siswa',`<form id="studentForm" class="form-grid"><label>Akun siswa<select name="id" required><option value="">Pilih siswa</option>${(students||[]).map(x=>`<option value="${x.id}" ${existing?.id===x.id?'selected':''}>${esc(x.full_name)} - ${esc(x.email)}</option>`).join('')}</select></label><label>NIS<input name="nis" value="${esc(existing?.nis||'')}" required></label><label>Kelas<input name="class_name" value="${esc(existing?.class_name||'XI')}" required></label><label>Tempat PKL/KPH/BKPH/RPH<input name="internship_place" value="${esc(existing?.internship_place||'')}" required></label><label>Guru pembimbing<select name="teacher_id"><option value="">Pilih guru</option>${(teachers||[]).map(x=>`<option value="${x.id}" ${existing?.teacher_id===x.id?'selected':''}>${esc(x.full_name)}</option>`).join('')}</select></label><label>Pembimbing lapangan<select name="field_supervisor_id"><option value="">Pilih pembimbing</option>${(fields||[]).map(x=>`<option value="${x.id}" ${existing?.field_supervisor_id===x.id?'selected':''}>${esc(x.full_name)}</option>`).join('')}</select></label><label>Tanggal mulai<input name="start_date" type="date" value="${existing?.start_date||''}"></label><label>Tanggal selesai<input name="end_date" type="date" value="${existing?.end_date||''}"></label><div class="wide actions"><button class="btn primary">Simpan</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);
 $('#studentForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.teacher_id=f.teacher_id||null;f.field_supervisor_id=f.field_supervisor_id||null;f.start_date=f.start_date||null;f.end_date=f.end_date||null;const {error}=await sb.from('student_details').upsert(f,{onConflict:'id'});if(error)return toast(error.message);closeModal();toast('Data siswa disimpan');renderStudents()};bindModalClose();
}

async function renderJournals(){
 let q=sb.from('daily_journals').select('*,student:profiles!daily_journals_student_id_fkey(full_name),validator:profiles!daily_journals_validated_by_fkey(full_name)').order('journal_date',{ascending:false});
 if(state.profile.role==='student')q=q.eq('student_id',state.profile.id);
 const {data,error}=await q;if(error)throw error;state.journals=data||[];
 const canAdd=state.profile.role==='student';
 $('#content').innerHTML=`<div class="section-head"><h3>${canAdd?'Jurnal Harian Saya':'Daftar Jurnal Siswa'}</h3>${canAdd?'<button class="btn primary" id="addJournalBtn">Isi Jurnal</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Siswa</th><th>Kegiatan</th><th>Tahapan</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${state.journals.map(j=>`<tr><td>${esc(j.journal_date)}</td><td>${esc(j.student?.full_name||state.profile.full_name)}</td><td>${esc(j.activity_title)}</td><td>${esc((j.activity_stages||[]).join(', '))}</td><td>${statusBadge(j.status)}</td><td><div class="actions">${canAdd&&['draft','revision'].includes(j.status)?`<button class="btn secondary edit-journal" data-id="${j.id}">Edit</button>`:''}${!canAdd&&j.status==='submitted'?`<button class="btn primary validate-journal" data-id="${j.id}">Validasi</button>`:''}<button class="btn secondary view-journal" data-id="${j.id}">Lihat</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada jurnal.</td></tr>'}</tbody></table></div>`;
 if(canAdd)$('#addJournalBtn').onclick=()=>openJournalModal();document.querySelectorAll('.edit-journal').forEach(b=>b.onclick=()=>openJournalModal(state.journals.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.validate-journal').forEach(b=>b.onclick=()=>openValidation(state.journals.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.view-journal').forEach(b=>b.onclick=()=>viewJournal(state.journals.find(x=>x.id===b.dataset.id)));
}
function openJournalModal(j=null){const checks=stages.map(s=>`<label class="check-item"><input type="checkbox" name="stages" value="${esc(s)}" ${(j?.activity_stages||[]).includes(s)?'checked':''}>${esc(s)}</label>`).join('');modal(j?'Edit Jurnal':'Isi Jurnal Harian',`<form id="journalForm" class="form-grid"><label>Tanggal<input name="journal_date" type="date" value="${j?.journal_date||new Date().toISOString().slice(0,10)}" required></label><label>Jam kegiatan<input name="work_hours" type="number" min="1" max="12" value="${j?.work_hours||7}"></label><label>Lokasi<input name="location" value="${esc(j?.location||'')}" required></label><label>Cuaca<input name="weather" value="${esc(j?.weather||'')}"></label><label class="wide">Judul kegiatan<input name="activity_title" value="${esc(j?.activity_title||'')}" required></label><label class="wide">Uraian kegiatan<textarea name="description" required>${esc(j?.description||'')}</textarea></label><div class="wide"><strong>Tahapan Kegiatan Perhutani</strong><div class="check-grid">${checks}</div></div><label class="wide">Pengetahuan/keterampilan<textarea name="learning">${esc(j?.learning||'')}</textarea></label><label class="wide">Kendala dan solusi<textarea name="obstacles">${esc(j?.obstacles||'')}</textarea></label><label class="wide">Refleksi<textarea name="reflection">${esc(j?.reflection||'')}</textarea></label><div class="wide actions"><button type="button" id="saveDraft" class="btn secondary">Simpan Draf</button><button class="btn primary">Kirim ke Pembimbing</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);const save=async status=>{const form=$('#journalForm');if(!form.reportValidity())return;const fd=new FormData(form);const row={student_id:state.profile.id,journal_date:fd.get('journal_date'),work_hours:Number(fd.get('work_hours')||0),location:fd.get('location'),weather:fd.get('weather'),activity_title:fd.get('activity_title'),description:fd.get('description'),activity_stages:fd.getAll('stages'),learning:fd.get('learning'),obstacles:fd.get('obstacles'),reflection:fd.get('reflection'),status};if(j)row.id=j.id;const {error}=await sb.from('daily_journals').upsert(row);if(error)return toast(error.message);closeModal();toast(status==='draft'?'Draf disimpan':'Jurnal dikirim');renderJournals()};$('#journalForm').onsubmit=e=>{e.preventDefault();save('submitted')};$('#saveDraft').onclick=()=>save('draft');bindModalClose()}
function openValidation(j){modal('Validasi Jurnal',`<p><strong>${esc(j.student?.full_name)}</strong> — ${esc(j.journal_date)}</p><div class="card"><h3>${esc(j.activity_title)}</h3><p>${esc(j.description)}</p><p><strong>Tahapan:</strong> ${esc((j.activity_stages||[]).join(', '))}</p></div><form id="validationForm" class="form-stack"><label>Catatan pembimbing<textarea name="supervisor_note">${esc(j.supervisor_note||'')}</textarea></label><div class="actions"><button type="button" data-status="approved" class="btn primary vbtn">Setujui</button><button type="button" data-status="revision" class="btn warn vbtn">Minta Perbaikan</button><button type="button" data-status="rejected" class="btn danger vbtn">Tolak</button></div></form>`);document.querySelectorAll('.vbtn').forEach(b=>b.onclick=async()=>{const note=new FormData($('#validationForm')).get('supervisor_note');const {error}=await sb.from('daily_journals').update({status:b.dataset.status,supervisor_note:note,validated_by:state.profile.id,validated_at:new Date().toISOString()}).eq('id',j.id);if(error)return toast(error.message);closeModal();toast('Status jurnal diperbarui');renderJournals()})}
function viewJournal(j){modal('Detail Jurnal',`<p><strong>Tanggal:</strong> ${esc(j.journal_date)}</p><p><strong>Siswa:</strong> ${esc(j.student?.full_name||state.profile.full_name)}</p><p><strong>Lokasi:</strong> ${esc(j.location)}</p><h3>${esc(j.activity_title)}</h3><p>${esc(j.description)}</p><p><strong>Tahapan:</strong> ${esc((j.activity_stages||[]).join(', '))}</p><p><strong>Pengetahuan/keterampilan:</strong> ${esc(j.learning||'-')}</p><p><strong>Kendala:</strong> ${esc(j.obstacles||'-')}</p><p><strong>Refleksi:</strong> ${esc(j.reflection||'-')}</p><p><strong>Status:</strong> ${statusBadge(j.status)}</p><p><strong>Catatan pembimbing:</strong> ${esc(j.supervisor_note||'-')}</p>`);bindModalClose()}

async function renderAttendance(){let q=sb.from('attendance').select('*,student:profiles!attendance_student_id_fkey(full_name)').order('attendance_date',{ascending:false});if(state.profile.role==='student')q=q.eq('student_id',state.profile.id);const {data,error}=await q;if(error)throw error;state.attendance=data||[];const canAdd=state.profile.role==='student';$('#content').innerHTML=`<div class="section-head"><h3>Presensi PKL</h3>${canAdd?'<button class="btn primary" id="addAttendance">Isi Presensi</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Siswa</th><th>Masuk</th><th>Pulang</th><th>Status</th><th>Lokasi</th></tr></thead><tbody>${state.attendance.map(a=>`<tr><td>${esc(a.attendance_date)}</td><td>${esc(a.student?.full_name||state.profile.full_name)}</td><td>${esc(a.check_in||'-')}</td><td>${esc(a.check_out||'-')}</td><td>${esc(a.presence_status)}</td><td>${esc(a.location||'-')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada presensi.</td></tr>'}</tbody></table></div>`;if(canAdd)$('#addAttendance').onclick=()=>openAttendance()}
function openAttendance(){const today=new Date().toISOString().slice(0,10);modal('Isi Presensi',`<form id="attendanceForm" class="form-grid"><label>Tanggal<input name="attendance_date" type="date" value="${today}" required></label><label>Status<select name="presence_status"><option>Hadir</option><option>Sakit</option><option>Izin</option><option>Tanpa Keterangan</option><option>Dinas Luar</option></select></label><label>Jam masuk<input name="check_in" type="time"></label><label>Jam pulang<input name="check_out" type="time"></label><label class="wide">Lokasi<input name="location"></label><label class="wide">Catatan<textarea name="notes"></textarea></label><div class="wide actions"><button class="btn primary">Simpan</button><button type="button" class="btn secondary modal-close">Batal</button></div></form>`);$('#attendanceForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.student_id=state.profile.id;f.check_in=f.check_in||null;f.check_out=f.check_out||null;const {error}=await sb.from('attendance').upsert(f,{onConflict:'student_id,attendance_date'});if(error)return toast(error.message);closeModal();toast('Presensi disimpan');renderAttendance()};bindModalClose()}

async function renderReports(){let q=sb.from('daily_journals').select('journal_date,activity_title,activity_stages,status,work_hours,student:profiles!daily_journals_student_id_fkey(full_name)').order('journal_date');if(state.profile.role==='student')q=q.eq('student_id',state.profile.id);const {data,error}=await q;if(error)throw error;const rows=data||[];const hours=rows.reduce((a,b)=>a+(Number(b.work_hours)||0),0);$('#content').innerHTML=`<div class="cards"><div class="card stat"><strong>${rows.length}</strong><span>Total jurnal</span></div><div class="card stat"><strong>${hours}</strong><span>Total jam kegiatan</span></div></div><div class="section-head"><h3>Rekap Laporan</h3><div class="actions"><button class="btn secondary" id="exportCsv">Ekspor CSV</button><button class="btn primary" id="printReport">Cetak/PDF</button></div></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Siswa</th><th>Kegiatan</th><th>Tahapan</th><th>Status</th><th>Jam</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.journal_date)}</td><td>${esc(r.student?.full_name||state.profile.full_name)}</td><td>${esc(r.activity_title)}</td><td>${esc((r.activity_stages||[]).join(', '))}</td><td>${statusBadge(r.status)}</td><td>${esc(r.work_hours||0)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada data.</td></tr>'}</tbody></table></div>`;$('#printReport').onclick=()=>window.print();$('#exportCsv').onclick=()=>downloadCsv(rows)}
function downloadCsv(rows){const head=['Tanggal','Siswa','Kegiatan','Tahapan','Status','Jam'];const body=rows.map(r=>[r.journal_date,r.student?.full_name||state.profile.full_name,r.activity_title,(r.activity_stages||[]).join('; '),r.status,r.work_hours||0]);const csv=[head,...body].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rekap-jurnal-pkl.csv';a.click();URL.revokeObjectURL(a.href)}

async function api(url,body){const token=state.session?.access_token;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Respons server tidak valid'}));if(!r.ok&&!j.error)j.error='Permintaan gagal';return j}
function modal(title,html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close-btn modal-close">✕</button></div>${html}</div></div>`);bindModalClose()}
function closeModal(){$('#modalBackdrop')?.remove()}
function bindModalClose(){document.querySelectorAll('.modal-close').forEach(b=>b.onclick=closeModal)}

init();
